# Generated by Django 4.0.2 on 2022-02-09 00:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=64)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('R', 'Resuelto')], default='P', max_length=1)),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='D:\\Proyectos\\TestNewsan\\TestNewsan\\media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'png', 'jpg'], message='Formatos soportados (pdf, doc, docx, png, jpg)')])),
            ],
        ),
    ]
